-- 001_Initial_Creations.sql
-- Reverse-engineered from EDD.API models (EDD.API/Models/*.cs) and Supabase PostgREST usage.
-- Run once on a new Supabase/Postgres database. Adjust RLS policies in the Supabase dashboard as needed.

-- =============================================================================
-- transit_times — SupabaseDataClient.FindTransitTimeAsync
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.transit_times (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin text NOT NULL,
  destination text NOT NULL,
  mode text NOT NULL,
  service_type text NOT NULL,
  transit_days integer NOT NULL
);

COMMENT ON TABLE public.transit_times IS
  'Lane-level base transit working days (EDD.API.Models.TransitTime).';
COMMENT ON COLUMN public.transit_times.transit_days IS
  'Count consumed by CalendarService.AddWorkingDaysWithNotesAsync (working days, not naive calendar).';

CREATE INDEX IF NOT EXISTS idx_transit_times_lane
  ON public.transit_times (origin, destination, mode, service_type);

-- =============================================================================
-- edd_rules — SupabaseDataClient.GetActiveRulesOrderedAsync
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.edd_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  priority integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  rule_type text NOT NULL,
  rule_json jsonb NOT NULL,
  version text NOT NULL DEFAULT '1',
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.edd_rules IS
  'Data-driven rules (EDD.API.Models.EddRule); JSON shape EDD.API.Models.Dtos.RuleDefinition.';
COMMENT ON COLUMN public.edd_rules.rule_json IS
  'conditions + actions consumed by RuleEngine.';

CREATE INDEX IF NOT EXISTS idx_edd_rules_active_priority
  ON public.edd_rules (is_active, priority);

-- =============================================================================
-- holidays — SupabaseDataClient.GetHolidayDatesForCountryAsync
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.holidays (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country text NOT NULL,
  holiday_date date NOT NULL,
  description text
);

COMMENT ON TABLE public.holidays IS
  'Country-scoped non-working dates (EDD.API.Models.Holiday).';

CREATE INDEX IF NOT EXISTS idx_holidays_country_date
  ON public.holidays (country, holiday_date);

-- =============================================================================
-- edd_logs — SupabaseDataClient.InsertEddLogAsync
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.edd_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  origin text NOT NULL,
  destination text NOT NULL,
  mode text NOT NULL,
  service_type text NOT NULL,
  pickup_date timestamptz NOT NULL,
  calculated_edd timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  applied_rules jsonb NOT NULL DEFAULT '[]'::jsonb,
  non_delivery_days_skipped integer NOT NULL DEFAULT 0
);

COMMENT ON TABLE public.edd_logs IS
  'Per-request calculate audit (EDD.API.Models.EddLog).';
COMMENT ON COLUMN public.edd_logs.applied_rules IS
  'Ordered rule names and non-working-day messages (API appliedRules).';
COMMENT ON COLUMN public.edd_logs.non_delivery_days_skipped IS
  'Total non-working calendar days crossed (API nonDeliveryDaysSkipped).';

CREATE INDEX IF NOT EXISTS idx_edd_logs_created_at
  ON public.edd_logs (created_at DESC);
